openapi: 3.0.0
info:
  title: Find AnonimizationFields API endpoint
  version: '2023-10-31'
paths:
  /api/elastic_assistant/anonimization_fields/_find:
    get:
      operationId: FindAnonimizationFields
      x-codegen-enabled: true
      description: Finds anonimization fields that match the given query.
      summary: Finds anonimization fields that match the given query.
      tags:
        - AnonimizationFields API
      parameters:
        - name: 'fields'
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: 'filter'
          in: query
          description: Search query
          required: false
          schema:
            type: string
        - name: 'sort_field'
          in: query
          description: Field to sort by
          required: false
          schema:
            $ref: '#/components/schemas/FindAnonimizationFieldsSortField'
        - name: 'sort_order'
          in: query
          description: Sort order
          required: false
          schema:
            $ref: '#/components/schemas/SortOrder'
        - name: 'page'
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: 'per_page'
          in: query
          description: AnonimizationFields per page
          required: false
          schema:
            type: integer
            minimum: 0
            default: 20

      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  perPage:
                    type: integer
                  total:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: './bulk_crud_anonimization_fields_route.schema.yaml#/components/schemas/AnonimizationFieldResponse'
                required:
                  - page
                  - perPage
                  - total
                  - data
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  error:
                    type: string
                  message:
                    type: string

components:
  schemas:
    FindAnonimizationFieldsSortField:
      type: string
      enum:
        - 'created_at'
        - 'is_default'
        - 'title'
        - 'updated_at'

    SortOrder:
      type: string
      enum:
        - 'asc'
        - 'desc'
